name: churn_intelligence
version: "1.0.0"
profile: churn_intelligence
model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  churn_intelligence:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: mart
    ml:
      +materialized: table
      +schema: ml
    monitoring:
      +materialized: table
      +schema: monitoring
